/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as AuthenticatedMeuPainelRouteImport } from './routes/_authenticated/meu-painel'
import { Route as AuthenticatedLancamentosIndexRouteImport } from './routes/_authenticated/lancamentos.index'
import { Route as AuthenticatedIndicadoresIndexRouteImport } from './routes/_authenticated/indicadores.index'
import { Route as AuthenticatedLancamentosNovoRouteImport } from './routes/_authenticated/lancamentos.novo'
import { Route as AuthenticatedLancamentosIdRouteImport } from './routes/_authenticated/lancamentos.$id'
import { Route as AuthenticatedIndicadoresNovoRouteImport } from './routes/_authenticated/indicadores.novo'
import { Route as AuthenticatedIndicadoresIdRouteImport } from './routes/_authenticated/indicadores.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPainelRoute = AuthenticatedMeuPainelRouteImport.update({
  id: '/meu-painel',
  path: '/meu-painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosIndexRoute =
  AuthenticatedLancamentosIndexRouteImport.update({
    id: '/lancamentos/',
    path: '/lancamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIndexRoute =
  AuthenticatedIndicadoresIndexRouteImport.update({
    id: '/indicadores/',
    path: '/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosNovoRoute =
  AuthenticatedLancamentosNovoRouteImport.update({
    id: '/lancamentos/novo',
    path: '/lancamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosIdRoute =
  AuthenticatedLancamentosIdRouteImport.update({
    id: '/lancamentos/$id',
    path: '/lancamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresNovoRoute =
  AuthenticatedIndicadoresNovoRouteImport.update({
    id: '/indicadores/novo',
    path: '/indicadores/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIdRoute =
  AuthenticatedIndicadoresIdRouteImport.update({
    id: '/indicadores/$id',
    path: '/indicadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/indicadores/$id': typeof AuthenticatedIndicadoresIdRoute
  '/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/indicadores/$id': typeof AuthenticatedIndicadoresIdRoute
  '/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/indicadores': typeof AuthenticatedIndicadoresIndexRoute
  '/lancamentos': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/indicadores/$id': typeof AuthenticatedIndicadoresIdRoute
  '/_authenticated/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/_authenticated/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/_authenticated/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/_authenticated/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/_authenticated/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meu-painel'
    | '/visao-geral'
    | '/indicadores/$id'
    | '/indicadores/novo'
    | '/lancamentos/$id'
    | '/lancamentos/novo'
    | '/indicadores/'
    | '/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meu-painel'
    | '/visao-geral'
    | '/indicadores/$id'
    | '/indicadores/novo'
    | '/lancamentos/$id'
    | '/lancamentos/novo'
    | '/indicadores'
    | '/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/meu-painel'
    | '/_authenticated/visao-geral'
    | '/_authenticated/indicadores/$id'
    | '/_authenticated/indicadores/novo'
    | '/_authenticated/lancamentos/$id'
    | '/_authenticated/lancamentos/novo'
    | '/_authenticated/indicadores/'
    | '/_authenticated/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-painel': {
      id: '/_authenticated/meu-painel'
      path: '/meu-painel'
      fullPath: '/meu-painel'
      preLoaderRoute: typeof AuthenticatedMeuPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/': {
      id: '/_authenticated/lancamentos/'
      path: '/lancamentos'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof AuthenticatedLancamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/': {
      id: '/_authenticated/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof AuthenticatedIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/novo': {
      id: '/_authenticated/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/lancamentos/novo'
      preLoaderRoute: typeof AuthenticatedLancamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/$id': {
      id: '/_authenticated/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/lancamentos/$id'
      preLoaderRoute: typeof AuthenticatedLancamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/novo': {
      id: '/_authenticated/indicadores/novo'
      path: '/indicadores/novo'
      fullPath: '/indicadores/novo'
      preLoaderRoute: typeof AuthenticatedIndicadoresNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/$id': {
      id: '/_authenticated/indicadores/$id'
      path: '/indicadores/$id'
      fullPath: '/indicadores/$id'
      preLoaderRoute: typeof AuthenticatedIndicadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeuPainelRoute: typeof AuthenticatedMeuPainelRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedIndicadoresIdRoute: typeof AuthenticatedIndicadoresIdRoute
  AuthenticatedIndicadoresNovoRoute: typeof AuthenticatedIndicadoresNovoRoute
  AuthenticatedLancamentosIdRoute: typeof AuthenticatedLancamentosIdRoute
  AuthenticatedLancamentosNovoRoute: typeof AuthenticatedLancamentosNovoRoute
  AuthenticatedIndicadoresIndexRoute: typeof AuthenticatedIndicadoresIndexRoute
  AuthenticatedLancamentosIndexRoute: typeof AuthenticatedLancamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeuPainelRoute: AuthenticatedMeuPainelRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedIndicadoresIdRoute: AuthenticatedIndicadoresIdRoute,
  AuthenticatedIndicadoresNovoRoute: AuthenticatedIndicadoresNovoRoute,
  AuthenticatedLancamentosIdRoute: AuthenticatedLancamentosIdRoute,
  AuthenticatedLancamentosNovoRoute: AuthenticatedLancamentosNovoRoute,
  AuthenticatedIndicadoresIndexRoute: AuthenticatedIndicadoresIndexRoute,
  AuthenticatedLancamentosIndexRoute: AuthenticatedLancamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
