/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAuditoriaDadosRouteImport } from './routes/_authenticated/auditoria-dados'
import { Route as AuthenticatedChamadosRouteImport } from './routes/_authenticated/chamados'
import { Route as AuthenticatedClassificacaoEscopoRouteImport } from './routes/_authenticated/classificacao-escopo'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDesempenhoFranquiasRouteImport } from './routes/_authenticated/desempenho-franquias'
import { Route as AuthenticatedIndicadoresFranquiaRouteImport } from './routes/_authenticated/indicadores-franquia'
import { Route as AuthenticatedLancamentosFranquiaRouteImport } from './routes/_authenticated/lancamentos-franquia'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMetasFranquiaRouteImport } from './routes/_authenticated/metas-franquia'
import { Route as AuthenticatedMeuPainelRouteImport } from './routes/_authenticated/meu-painel'
import { Route as AuthenticatedMeusIndicadoresRouteImport } from './routes/_authenticated/meus-indicadores'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as AuthenticatedFranquiasIndexRouteImport } from './routes/_authenticated/franquias.index'
import { Route as AuthenticatedFranquiasIdRouteImport } from './routes/_authenticated/franquias.$id'
import { Route as AuthenticatedIndicadoresIndexRouteImport } from './routes/_authenticated/indicadores.index'
import { Route as AuthenticatedIndicadoresIdRouteImport } from './routes/_authenticated/indicadores.$id'
import { Route as AuthenticatedIndicadoresNovoRouteImport } from './routes/_authenticated/indicadores.novo'
import { Route as AuthenticatedLancamentosIndexRouteImport } from './routes/_authenticated/lancamentos.index'
import { Route as AuthenticatedLancamentosIdRouteImport } from './routes/_authenticated/lancamentos.$id'
import { Route as AuthenticatedLancamentosNovoRouteImport } from './routes/_authenticated/lancamentos.novo'
import { Route as AuthenticatedSetoresIndexRouteImport } from './routes/_authenticated/setores.index'
import { Route as AuthenticatedSetoresIdRouteImport } from './routes/_authenticated/setores.$id'
import { Route as AuthenticatedFranquiasIdIndexRouteImport } from './routes/_authenticated/franquias.$id.index'
import { Route as AuthenticatedIndicadoresIdEditarRouteImport } from './routes/_authenticated/indicadores.$id.editar'
import { Route as AuthenticatedFranquiasIdIndicadoresNovoRouteImport } from './routes/_authenticated/franquias.$id.indicadores.novo'
import { Route as AuthenticatedFranquiasIdIndicadoresIndIdIndexRouteImport } from './routes/_authenticated/franquias.$id.indicadores.$indId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaDadosRoute =
  AuthenticatedAuditoriaDadosRouteImport.update({
    id: '/auditoria-dados',
    path: '/auditoria-dados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosRoute = AuthenticatedChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassificacaoEscopoRoute =
  AuthenticatedClassificacaoEscopoRouteImport.update({
    id: '/classificacao-escopo',
    path: '/classificacao-escopo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesempenhoFranquiasRoute =
  AuthenticatedDesempenhoFranquiasRouteImport.update({
    id: '/desempenho-franquias',
    path: '/desempenho-franquias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresFranquiaRoute =
  AuthenticatedIndicadoresFranquiaRouteImport.update({
    id: '/indicadores-franquia',
    path: '/indicadores-franquia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosFranquiaRoute =
  AuthenticatedLancamentosFranquiaRouteImport.update({
    id: '/lancamentos-franquia',
    path: '/lancamentos-franquia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasFranquiaRoute =
  AuthenticatedMetasFranquiaRouteImport.update({
    id: '/metas-franquia',
    path: '/metas-franquia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuPainelRoute = AuthenticatedMeuPainelRouteImport.update({
  id: '/meu-painel',
  path: '/meu-painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusIndicadoresRoute =
  AuthenticatedMeusIndicadoresRouteImport.update({
    id: '/meus-indicadores',
    path: '/meus-indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFranquiasIndexRoute =
  AuthenticatedFranquiasIndexRouteImport.update({
    id: '/franquias/',
    path: '/franquias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFranquiasIdRoute =
  AuthenticatedFranquiasIdRouteImport.update({
    id: '/franquias/$id',
    path: '/franquias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIndexRoute =
  AuthenticatedIndicadoresIndexRouteImport.update({
    id: '/indicadores/',
    path: '/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIdRoute =
  AuthenticatedIndicadoresIdRouteImport.update({
    id: '/indicadores/$id',
    path: '/indicadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresNovoRoute =
  AuthenticatedIndicadoresNovoRouteImport.update({
    id: '/indicadores/novo',
    path: '/indicadores/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosIndexRoute =
  AuthenticatedLancamentosIndexRouteImport.update({
    id: '/lancamentos/',
    path: '/lancamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosIdRoute =
  AuthenticatedLancamentosIdRouteImport.update({
    id: '/lancamentos/$id',
    path: '/lancamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosNovoRoute =
  AuthenticatedLancamentosNovoRouteImport.update({
    id: '/lancamentos/novo',
    path: '/lancamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetoresIndexRoute =
  AuthenticatedSetoresIndexRouteImport.update({
    id: '/setores/',
    path: '/setores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetoresIdRoute = AuthenticatedSetoresIdRouteImport.update({
  id: '/setores/$id',
  path: '/setores/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFranquiasIdIndexRoute =
  AuthenticatedFranquiasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFranquiasIdRoute,
  } as any)
const AuthenticatedIndicadoresIdEditarRoute =
  AuthenticatedIndicadoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedIndicadoresIdRoute,
  } as any)
const AuthenticatedFranquiasIdIndicadoresNovoRoute =
  AuthenticatedFranquiasIdIndicadoresNovoRouteImport.update({
    id: '/indicadores/novo',
    path: '/indicadores/novo',
    getParentRoute: () => AuthenticatedFranquiasIdRoute,
  } as any)
const AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute =
  AuthenticatedFranquiasIdIndicadoresIndIdIndexRouteImport.update({
    id: '/indicadores/$indId/',
    path: '/indicadores/$indId/',
    getParentRoute: () => AuthenticatedFranquiasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/auditoria-dados': typeof AuthenticatedAuditoriaDadosRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/classificacao-escopo': typeof AuthenticatedClassificacaoEscopoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desempenho-franquias': typeof AuthenticatedDesempenhoFranquiasRoute
  '/indicadores-franquia': typeof AuthenticatedIndicadoresFranquiaRoute
  '/lancamentos-franquia': typeof AuthenticatedLancamentosFranquiaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/metas-franquia': typeof AuthenticatedMetasFranquiaRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meus-indicadores': typeof AuthenticatedMeusIndicadoresRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/franquias/$id': typeof AuthenticatedFranquiasIdRouteWithChildren
  '/indicadores/$id': typeof AuthenticatedIndicadoresIdRouteWithChildren
  '/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/franquias/': typeof AuthenticatedFranquiasIndexRoute
  '/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
  '/setores/': typeof AuthenticatedSetoresIndexRoute
  '/indicadores/$id/editar': typeof AuthenticatedIndicadoresIdEditarRoute
  '/franquias/$id/': typeof AuthenticatedFranquiasIdIndexRoute
  '/franquias/$id/indicadores/novo': typeof AuthenticatedFranquiasIdIndicadoresNovoRoute
  '/franquias/$id/indicadores/$indId/': typeof AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/auditoria-dados': typeof AuthenticatedAuditoriaDadosRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/classificacao-escopo': typeof AuthenticatedClassificacaoEscopoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desempenho-franquias': typeof AuthenticatedDesempenhoFranquiasRoute
  '/indicadores-franquia': typeof AuthenticatedIndicadoresFranquiaRoute
  '/lancamentos-franquia': typeof AuthenticatedLancamentosFranquiaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/metas-franquia': typeof AuthenticatedMetasFranquiaRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meus-indicadores': typeof AuthenticatedMeusIndicadoresRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/indicadores/$id': typeof AuthenticatedIndicadoresIdRouteWithChildren
  '/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/franquias': typeof AuthenticatedFranquiasIndexRoute
  '/indicadores': typeof AuthenticatedIndicadoresIndexRoute
  '/lancamentos': typeof AuthenticatedLancamentosIndexRoute
  '/setores': typeof AuthenticatedSetoresIndexRoute
  '/indicadores/$id/editar': typeof AuthenticatedIndicadoresIdEditarRoute
  '/franquias/$id': typeof AuthenticatedFranquiasIdIndexRoute
  '/franquias/$id/indicadores/novo': typeof AuthenticatedFranquiasIdIndicadoresNovoRoute
  '/franquias/$id/indicadores/$indId': typeof AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/auditoria-dados': typeof AuthenticatedAuditoriaDadosRoute
  '/_authenticated/chamados': typeof AuthenticatedChamadosRoute
  '/_authenticated/classificacao-escopo': typeof AuthenticatedClassificacaoEscopoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/desempenho-franquias': typeof AuthenticatedDesempenhoFranquiasRoute
  '/_authenticated/indicadores-franquia': typeof AuthenticatedIndicadoresFranquiaRoute
  '/_authenticated/lancamentos-franquia': typeof AuthenticatedLancamentosFranquiaRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/metas-franquia': typeof AuthenticatedMetasFranquiaRoute
  '/_authenticated/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/_authenticated/meus-indicadores': typeof AuthenticatedMeusIndicadoresRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/franquias/$id': typeof AuthenticatedFranquiasIdRouteWithChildren
  '/_authenticated/indicadores/$id': typeof AuthenticatedIndicadoresIdRouteWithChildren
  '/_authenticated/indicadores/novo': typeof AuthenticatedIndicadoresNovoRoute
  '/_authenticated/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/_authenticated/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/_authenticated/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/_authenticated/franquias/': typeof AuthenticatedFranquiasIndexRoute
  '/_authenticated/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/_authenticated/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
  '/_authenticated/setores/': typeof AuthenticatedSetoresIndexRoute
  '/_authenticated/indicadores/$id/editar': typeof AuthenticatedIndicadoresIdEditarRoute
  '/_authenticated/franquias/$id/': typeof AuthenticatedFranquiasIdIndexRoute
  '/_authenticated/franquias/$id/indicadores/novo': typeof AuthenticatedFranquiasIdIndicadoresNovoRoute
  '/_authenticated/franquias/$id/indicadores/$indId/': typeof AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/auditoria'
    | '/auditoria-dados'
    | '/chamados'
    | '/classificacao-escopo'
    | '/configuracoes'
    | '/desempenho-franquias'
    | '/indicadores-franquia'
    | '/lancamentos-franquia'
    | '/metas'
    | '/metas-franquia'
    | '/meu-painel'
    | '/meus-indicadores'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/visao-geral'
    | '/franquias/$id'
    | '/indicadores/$id'
    | '/indicadores/novo'
    | '/lancamentos/$id'
    | '/lancamentos/novo'
    | '/setores/$id'
    | '/franquias/'
    | '/indicadores/'
    | '/lancamentos/'
    | '/setores/'
    | '/indicadores/$id/editar'
    | '/franquias/$id/'
    | '/franquias/$id/indicadores/novo'
    | '/franquias/$id/indicadores/$indId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/auditoria'
    | '/auditoria-dados'
    | '/chamados'
    | '/classificacao-escopo'
    | '/configuracoes'
    | '/desempenho-franquias'
    | '/indicadores-franquia'
    | '/lancamentos-franquia'
    | '/metas'
    | '/metas-franquia'
    | '/meu-painel'
    | '/meus-indicadores'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/visao-geral'
    | '/indicadores/$id'
    | '/indicadores/novo'
    | '/lancamentos/$id'
    | '/lancamentos/novo'
    | '/setores/$id'
    | '/franquias'
    | '/indicadores'
    | '/lancamentos'
    | '/setores'
    | '/indicadores/$id/editar'
    | '/franquias/$id'
    | '/franquias/$id/indicadores/novo'
    | '/franquias/$id/indicadores/$indId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/definir-senha'
    | '/_authenticated/auditoria'
    | '/_authenticated/auditoria-dados'
    | '/_authenticated/chamados'
    | '/_authenticated/classificacao-escopo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/desempenho-franquias'
    | '/_authenticated/indicadores-franquia'
    | '/_authenticated/lancamentos-franquia'
    | '/_authenticated/metas'
    | '/_authenticated/metas-franquia'
    | '/_authenticated/meu-painel'
    | '/_authenticated/meus-indicadores'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/visao-geral'
    | '/_authenticated/franquias/$id'
    | '/_authenticated/indicadores/$id'
    | '/_authenticated/indicadores/novo'
    | '/_authenticated/lancamentos/$id'
    | '/_authenticated/lancamentos/novo'
    | '/_authenticated/setores/$id'
    | '/_authenticated/franquias/'
    | '/_authenticated/indicadores/'
    | '/_authenticated/lancamentos/'
    | '/_authenticated/setores/'
    | '/_authenticated/indicadores/$id/editar'
    | '/_authenticated/franquias/$id/'
    | '/_authenticated/franquias/$id/indicadores/novo'
    | '/_authenticated/franquias/$id/indicadores/$indId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-dados': {
      id: '/_authenticated/auditoria-dados'
      path: '/auditoria-dados'
      fullPath: '/auditoria-dados'
      preLoaderRoute: typeof AuthenticatedAuditoriaDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados': {
      id: '/_authenticated/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof AuthenticatedChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classificacao-escopo': {
      id: '/_authenticated/classificacao-escopo'
      path: '/classificacao-escopo'
      fullPath: '/classificacao-escopo'
      preLoaderRoute: typeof AuthenticatedClassificacaoEscopoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho-franquias': {
      id: '/_authenticated/desempenho-franquias'
      path: '/desempenho-franquias'
      fullPath: '/desempenho-franquias'
      preLoaderRoute: typeof AuthenticatedDesempenhoFranquiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores-franquia': {
      id: '/_authenticated/indicadores-franquia'
      path: '/indicadores-franquia'
      fullPath: '/indicadores-franquia'
      preLoaderRoute: typeof AuthenticatedIndicadoresFranquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos-franquia': {
      id: '/_authenticated/lancamentos-franquia'
      path: '/lancamentos-franquia'
      fullPath: '/lancamentos-franquia'
      preLoaderRoute: typeof AuthenticatedLancamentosFranquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas-franquia': {
      id: '/_authenticated/metas-franquia'
      path: '/metas-franquia'
      fullPath: '/metas-franquia'
      preLoaderRoute: typeof AuthenticatedMetasFranquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-painel': {
      id: '/_authenticated/meu-painel'
      path: '/meu-painel'
      fullPath: '/meu-painel'
      preLoaderRoute: typeof AuthenticatedMeuPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-indicadores': {
      id: '/_authenticated/meus-indicadores'
      path: '/meus-indicadores'
      fullPath: '/meus-indicadores'
      preLoaderRoute: typeof AuthenticatedMeusIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/franquias/': {
      id: '/_authenticated/franquias/'
      path: '/franquias'
      fullPath: '/franquias/'
      preLoaderRoute: typeof AuthenticatedFranquiasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/franquias/$id': {
      id: '/_authenticated/franquias/$id'
      path: '/franquias/$id'
      fullPath: '/franquias/$id'
      preLoaderRoute: typeof AuthenticatedFranquiasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/': {
      id: '/_authenticated/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof AuthenticatedIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/$id': {
      id: '/_authenticated/indicadores/$id'
      path: '/indicadores/$id'
      fullPath: '/indicadores/$id'
      preLoaderRoute: typeof AuthenticatedIndicadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/novo': {
      id: '/_authenticated/indicadores/novo'
      path: '/indicadores/novo'
      fullPath: '/indicadores/novo'
      preLoaderRoute: typeof AuthenticatedIndicadoresNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/': {
      id: '/_authenticated/lancamentos/'
      path: '/lancamentos'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof AuthenticatedLancamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/$id': {
      id: '/_authenticated/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/lancamentos/$id'
      preLoaderRoute: typeof AuthenticatedLancamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/novo': {
      id: '/_authenticated/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/lancamentos/novo'
      preLoaderRoute: typeof AuthenticatedLancamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores/': {
      id: '/_authenticated/setores/'
      path: '/setores'
      fullPath: '/setores/'
      preLoaderRoute: typeof AuthenticatedSetoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores/$id': {
      id: '/_authenticated/setores/$id'
      path: '/setores/$id'
      fullPath: '/setores/$id'
      preLoaderRoute: typeof AuthenticatedSetoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/franquias/$id/': {
      id: '/_authenticated/franquias/$id/'
      path: '/'
      fullPath: '/franquias/$id/'
      preLoaderRoute: typeof AuthenticatedFranquiasIdIndexRouteImport
      parentRoute: typeof AuthenticatedFranquiasIdRoute
    }
    '/_authenticated/indicadores/$id/editar': {
      id: '/_authenticated/indicadores/$id/editar'
      path: '/editar'
      fullPath: '/indicadores/$id/editar'
      preLoaderRoute: typeof AuthenticatedIndicadoresIdEditarRouteImport
      parentRoute: typeof AuthenticatedIndicadoresIdRoute
    }
    '/_authenticated/franquias/$id/indicadores/novo': {
      id: '/_authenticated/franquias/$id/indicadores/novo'
      path: '/indicadores/novo'
      fullPath: '/franquias/$id/indicadores/novo'
      preLoaderRoute: typeof AuthenticatedFranquiasIdIndicadoresNovoRouteImport
      parentRoute: typeof AuthenticatedFranquiasIdRoute
    }
    '/_authenticated/franquias/$id/indicadores/$indId/': {
      id: '/_authenticated/franquias/$id/indicadores/$indId/'
      path: '/indicadores/$indId'
      fullPath: '/franquias/$id/indicadores/$indId/'
      preLoaderRoute: typeof AuthenticatedFranquiasIdIndicadoresIndIdIndexRouteImport
      parentRoute: typeof AuthenticatedFranquiasIdRoute
    }
  }
}

interface AuthenticatedFranquiasIdRouteChildren {
  AuthenticatedFranquiasIdIndexRoute: typeof AuthenticatedFranquiasIdIndexRoute
  AuthenticatedFranquiasIdIndicadoresNovoRoute: typeof AuthenticatedFranquiasIdIndicadoresNovoRoute
  AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute: typeof AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute
}

const AuthenticatedFranquiasIdRouteChildren: AuthenticatedFranquiasIdRouteChildren =
  {
    AuthenticatedFranquiasIdIndexRoute: AuthenticatedFranquiasIdIndexRoute,
    AuthenticatedFranquiasIdIndicadoresNovoRoute:
      AuthenticatedFranquiasIdIndicadoresNovoRoute,
    AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute:
      AuthenticatedFranquiasIdIndicadoresIndIdIndexRoute,
  }

const AuthenticatedFranquiasIdRouteWithChildren =
  AuthenticatedFranquiasIdRoute._addFileChildren(
    AuthenticatedFranquiasIdRouteChildren,
  )

interface AuthenticatedIndicadoresIdRouteChildren {
  AuthenticatedIndicadoresIdEditarRoute: typeof AuthenticatedIndicadoresIdEditarRoute
}

const AuthenticatedIndicadoresIdRouteChildren: AuthenticatedIndicadoresIdRouteChildren =
  {
    AuthenticatedIndicadoresIdEditarRoute:
      AuthenticatedIndicadoresIdEditarRoute,
  }

const AuthenticatedIndicadoresIdRouteWithChildren =
  AuthenticatedIndicadoresIdRoute._addFileChildren(
    AuthenticatedIndicadoresIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAuditoriaDadosRoute: typeof AuthenticatedAuditoriaDadosRoute
  AuthenticatedChamadosRoute: typeof AuthenticatedChamadosRoute
  AuthenticatedClassificacaoEscopoRoute: typeof AuthenticatedClassificacaoEscopoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDesempenhoFranquiasRoute: typeof AuthenticatedDesempenhoFranquiasRoute
  AuthenticatedIndicadoresFranquiaRoute: typeof AuthenticatedIndicadoresFranquiaRoute
  AuthenticatedLancamentosFranquiaRoute: typeof AuthenticatedLancamentosFranquiaRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMetasFranquiaRoute: typeof AuthenticatedMetasFranquiaRoute
  AuthenticatedMeuPainelRoute: typeof AuthenticatedMeuPainelRoute
  AuthenticatedMeusIndicadoresRoute: typeof AuthenticatedMeusIndicadoresRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedFranquiasIdRoute: typeof AuthenticatedFranquiasIdRouteWithChildren
  AuthenticatedIndicadoresIdRoute: typeof AuthenticatedIndicadoresIdRouteWithChildren
  AuthenticatedIndicadoresNovoRoute: typeof AuthenticatedIndicadoresNovoRoute
  AuthenticatedLancamentosIdRoute: typeof AuthenticatedLancamentosIdRoute
  AuthenticatedLancamentosNovoRoute: typeof AuthenticatedLancamentosNovoRoute
  AuthenticatedSetoresIdRoute: typeof AuthenticatedSetoresIdRoute
  AuthenticatedFranquiasIndexRoute: typeof AuthenticatedFranquiasIndexRoute
  AuthenticatedIndicadoresIndexRoute: typeof AuthenticatedIndicadoresIndexRoute
  AuthenticatedLancamentosIndexRoute: typeof AuthenticatedLancamentosIndexRoute
  AuthenticatedSetoresIndexRoute: typeof AuthenticatedSetoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAuditoriaDadosRoute: AuthenticatedAuditoriaDadosRoute,
  AuthenticatedChamadosRoute: AuthenticatedChamadosRoute,
  AuthenticatedClassificacaoEscopoRoute: AuthenticatedClassificacaoEscopoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDesempenhoFranquiasRoute: AuthenticatedDesempenhoFranquiasRoute,
  AuthenticatedIndicadoresFranquiaRoute: AuthenticatedIndicadoresFranquiaRoute,
  AuthenticatedLancamentosFranquiaRoute: AuthenticatedLancamentosFranquiaRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMetasFranquiaRoute: AuthenticatedMetasFranquiaRoute,
  AuthenticatedMeuPainelRoute: AuthenticatedMeuPainelRoute,
  AuthenticatedMeusIndicadoresRoute: AuthenticatedMeusIndicadoresRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedFranquiasIdRoute: AuthenticatedFranquiasIdRouteWithChildren,
  AuthenticatedIndicadoresIdRoute: AuthenticatedIndicadoresIdRouteWithChildren,
  AuthenticatedIndicadoresNovoRoute: AuthenticatedIndicadoresNovoRoute,
  AuthenticatedLancamentosIdRoute: AuthenticatedLancamentosIdRoute,
  AuthenticatedLancamentosNovoRoute: AuthenticatedLancamentosNovoRoute,
  AuthenticatedSetoresIdRoute: AuthenticatedSetoresIdRoute,
  AuthenticatedFranquiasIndexRoute: AuthenticatedFranquiasIndexRoute,
  AuthenticatedIndicadoresIndexRoute: AuthenticatedIndicadoresIndexRoute,
  AuthenticatedLancamentosIndexRoute: AuthenticatedLancamentosIndexRoute,
  AuthenticatedSetoresIndexRoute: AuthenticatedSetoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
